apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ BITBUCKET_REPO_SLUG }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
  labels:
    build: "{{ BITBUCKET_BUILD_NUMBER }}"
spec:
  tls:
    - hosts:
      - "{{ APP_DOMAIN }}"
      secretName: wehelpyou-tls
  rules:
    - host: "{{ APP_DOMAIN }}"
      http:
        paths:
          - path: /*
            backend:
              serviceName: app-{{ BITBUCKET_REPO_SLUG }}
              servicePort: 3000
